require "modules.packages"
require "core.options"
require "core.colorscheme"
require "core.keymaps"

require "modules.autopairs"
require "modules.comments"
require "modules.indentline"
require "modules.lualine"
require "modules.nvim-tree"
require "modules.treesitter"
require "modules.telescope"
require "modules.git-signs"
require "modules.cmp"
require "modules.lsp"
